### PR TITLE
Fix logic to using 'Y' as proceed variable and add .gitattributes to ignore list

### PR DESCRIPTION
**Pull request by afragen**

### CODE REVIEW

**Comment by GaryJones** [comment]
Why the requirement for a capital?

**Comment by afragen** [comment]
https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy/commit/41b7d2ea6a828fbdbb552bd9d4215a713e17956c added the 'Y' but the check for the response still had the lowercase 'y'. Perhaps, I'm not understanding the reasons for using the capital Y. That's why this is a PR and I didn't push myself, I'm unsure.

**Comment by GaryJones** [comment]
The uppercase Y is the accepted way for indicating the default response if you enter nothing and just hit enter. i.e. `Y / n` the default if just hitting enter would be result in the check being true.

**Comment by afragen** [comment]
In that case I'll pull this PR. Adding another for adding .gitattributes

**Pull request closed without merging**
