### PR TITLE
remove trunk as option for version

### PR DESCRIPTION
**Pull request by afragen**
This is not good practice per Mika and Otto

### CODE REVIEW

**Comment by defries** [comment]
What specifically is not good practice?

**Comment by afragen** [comment]
`Stable tag: trunk` it should be an actual version number

**Comment by GaryJones** [comment]
The PR seems to include non-related code changes.

**Comment by GaryJones** [comment]
> This is not good practice per Mika and Otto

While it may not be a good practice, it is currently allowed in the repo AFAIK.

**Comment by afragen** [comment]
> While it may not be a good practice, it is currently allowed in the repo AFAIK.

It is. The only real issue with having it there is that it removes our only check ensuring readme and version are in sync, but only if `Stable tag: trunk`

**Comment by afragen** [comment]
> The PR seems to include non-related code changes.

Yeah, sorry I'll fix it.

**Comment by afragen** [comment]
closed in favor of #23

**Comment by afragen** [comment]
Er #24

**Comment by ginsterbusch** [comment]
... are you done yet? :-1:

**Comment by GaryJones** [comment]
> Github is spamming me with your comments.

Feel free to Unsubscribe in the sidebar.

In the meantime, I appreciate the progressive running commentary, instead of editing one or two comments.

**Pull request closed without merging**
