### PR TITLE
remove trunk as readme version option

### PR DESCRIPTION
**Pull request by afragen**
this is best practice per repo maintainers.

Finally correct, sorry about the clutter. Use this PR in favor or #22

### CODE REVIEW

**Comment by GaryJones** [comment]
> this is best practice per repo maintainers.

Do you have a reference for this?

**Comment by nickcernis** [comment]
Otto has said in the past that using trunk is fine for simple plugins: https://wordpress.org/support/topic/upload-new-version-to-tags-andor-trunk?replies=9

> If you're not keeping old versions around for people, then simply updating trunk will be enough. This is the usual case for extremely simple plugins. In this case, you'd want "Stable Tag: trunk" in the readme.txt file.

I have a very simple plugin that uses trunk in this way; would prefer that it remained an option if possible.

**Comment by afragen** [comment]
I brought this topic up at WordCamp OC with @Ipstenu and was told that while it is acceptable, the best practice is to use the actual tag. This is the only motivation for this change.

BTW, in the overhaul of the plugin repo, the repo maintainers will be able to set the _Tested to_ directly. 

This seemed to be the major use case, but I could be wrong on this. @Otto42's comment above seems to be related to not keeping tags in the repo.

**Comment by GaryJones** [comment]
Although I've never used `trunk` as a `Stable` value, while it is allowed, I think this script should permit it.

**Pull request closed without merging**
